services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "DarkDevil"
      PASSWORD: "Aryan987"
      RAM_SIZE: "128G"
      CPU_CORES: "64"
      DISK_SIZE: "750G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    entrypoint: /bin/bash -c "ifconfig eth0 | grep 'inet ' | awk '{print \"Connect to IP: \"$2 \" with USERNAME: DarkDevil and PASSWORD: Aryan987\"}' && sleep infinity"

